name: FunctionalTests
on: [pull_request, push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel twine
      - name: Build and install package
        run: |
          python -m build 
          pip install -e .
      - name: Run functional tests
        run: |
          ./tests/e2e/test_add_three_users_and_one_equal_expense.sh
          ./tests/e2e/test_add_three_users_and_one_percentage_expense.sh
          ./tests/e2e/test_add_two_users_and_one_equal_expense.sh
          ./tests/e2e/test_add_two_users_and_one_percentage_expense.sh
          ./tests/e2e/test_add_two_users_and_one_value_expense.sh
